config/routes.rb
Rails.application.routes.draw do

  resources :restaurants

  resources :menus

  root 'restaurants#index'

end

app/models/create_restaurants_table.rb
class CreateRestaurantsTable < ActiveRecord::Base
end

app/models/menu.rb
class Menu < ActiveRecord::Base
	validates_presence_of :name ,:price
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
		validates_presence_of :name ,:location
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
	before_action :menu_get_one,:only=>[:edit,:destroy,:update,:show]
	before_action :menu_get_list,:only=>[:edit,:index]

	def index
		menu_get_list
		if params[:id]
			menu_get_one
		else
			@menu=Menu.new
		end
	end

	def show

	end

	def destroy
		@menu.destroy
		redirect_to menus_path(:page=>params[:page])
	end

	#POST menu/:id
	def create
		@menu=Menu.new(menu_juge_require)
		if @menu.save
			redirect_to menus_path
		else
			render :action=>:index
		end

	end

	def update
		if @menu.update(menu_juge_require)
			redirect_to menus_path(:page=>params[:page])
		else
			render :action=>:index
		end
	end

	private

	def menu_get_list
		@menus=Menu.page(params[:page]).per(5)
	end

	def menu_get_one
		@menu=Menu.find(params[:id])
	end

	def menu_juge_require
		params.require(:menu).permit(:name,:price,:remove_time,:ready_time,:ordderby,:tag)
	end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
	before_action :restaurant_find_one,:only=>[:show,:edit,:update,:destroy]
	#GET restaurant/
	def index
		# @restaurants=Restaurant.all
		@restaurants = Restaurant.page(params[:page]).per(5)
		#給new用
		@restaurant=Restaurant.new


	end
	#GET restaurant/:id
	def show
		# restaurant_find_one()
	end
	#GET restaurant/:id/edit
	def edit

		# restaurant_find_one()
		#直接將畫面展現出來
		@restaurants = Restaurant.page(params[:page]).per(5)
		# @restaurants[:page]=>2
		render :action=>:index
	end
	#GET restaurant/new
	def new
		@restaurant=Restaurant.new
	end
	#POST restaurant/
	def create
		@restaurants = Restaurant.page(params[:page]).per(5)
		@restaurant=Restaurant.new(restaurant_form)



		if @restaurant.save
			flash[:notice]="You have already save."
			redirect_to restaurants_path
		else
			render :action=>:index
		end
	end
	#PATCH restaurant/:id/edit
	def update
		# restaurant_find_one
		@restaurants = Restaurant.page(params[:page]).per(5)
		if @restaurant.update(restaurant_form)
			flash[:notice]="You have already save."
			redirect_to restaurants_path
		else
			render :action=>:index
		end
	end
	#DELETE restaurant/:id
	def destroy
		# @restaurant=Restaurant.find(params[:id])
		# restaurant_find_one()
		@restaurant.destroy
		redirect_to restaurants_path
	end

	private

	def restaurant_find_one
		@restaurant=Restaurant.find(params[:id])
	end
	#確定使用者不可以輸入其他的欄位
	def restaurant_form
		params.require(:restaurant).permit(:name,:location,:description,:minmoney,:uploadtime,:opening)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/menu_helper.rb
module MenuHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Restaurants</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">

	<% if flash[:notice].present? %>
	<p><%= flash[:notice] %></p>
	<% end%>
	<% if flash[:alert].present? %>
	<p><%= flash[:alert] %></p>
	<% end %>
	<%= yield %>
</div>
</body>
</html>

app/views/menus/_form.html.erb
			<%#=params.inspect%>
			<% if @menu.errors.any? %>
			      <ul class="row">
			      <% @menu.errors.full_messages.each do |msg| %>
			        <li><%= msg %></li>
			      <% end %>
			      </ul>
			<% end %>

			<div class="row">
				<div class="col-md-1">
					<%= f.label :name,"名字" %>
				</div>
				<div class="col-md-3">
					<%= f.text_field :name,:class=>"form-control" %>
				</div>
				<div class="col-md-1">
					<%= f.label :price,"價錢" %>
				</div>
				<div class="col-md-2">
					<%= f.number_field :price,:class=>"form-control" %>
				</div>
				<div class="col-md-1">
					<%= f.label :tag,"類型" %>
				</div>
				<div class="col-md-2">
					<%= f.number_field :tag,:class=>"form-control" %>
				</div>
				<div class="col-md-1">
					<%= f.label :orderby,"順序" %>
				</div>
				<div class="col-md-1">
					<%= f.number_field :orderby,:class=>"form-control" %>
				</div>
			</div>

			<div class="row">

				<div class="col-md-1">
					<%= f.label :ready_time,"上架時間" %>
				</div>
				<div class="col-md-2">
					<%= f.date_field :ready_time,:class=>"form-control" %>
				</div>
				<div class="col-md-1">
					<%= f.label :remove_time,"下架時間" %>
				</div>
				<div class="col-md-2">
					<%= f.date_field :remove_time,:class=>"form-control" %>
				</div>
			</div>
			<div class="row">
				<div class="col-md-12 text-center">

					<%= f.submit("送出") %>
				</div>
			</div>

app/views/menus/index.html.erb
	<div class="well">
		<div class="row">
			this is a menu col.
		</div>
	</div>

	  <div class="row">

		<%=form_for @menu do |f|%>
			<%= render :partial=>'form',:locals=>{ :f=>f} %>
		<% end %>
		</div>

<div class="row">
	<div class="col-md-12"><%= link_to "new",new_menu_path,:class=>"btn btn-default" %>
	</div>
</div>
<table class="table table-striped">
	<thead >
		<tr>
			<th class="col-md-2">名字</th>
			<th class="col-md-6">位置</th>
			<th class="col-md-4"></th>
		</tr>
	</thead><!--thead-->
	<tbody class="tbody">
		<% @menus.each do |f| %>
		<tr >
			<td class="col-md-2"><%=f.name %></td>
			<td class="col-md-6"><%=f.price%></td>
			<td class="col-md-4">
				<div class="btn-group">
						<%= link_to "show", menu_path(f),:class=>"btn btn-primary" %>
						<%= link_to "edit", menus_path(:id=>f,:page => params[:page]),:class=>"btn btn-default" %>
						<%= link_to "delete", menu_path(f, :page => params[:page] ),:method=>:delete,:class=>"btn btn-danger" %>
				</div><!--btn-group-->
			</td>
		</tr>
	<% end %>
	</tbody><!--tbody-->
</table><!--table-->
<div class="row">
	<div class="col-md-12 text-center"><%= paginate @menus %></div>
</div>

app/views/menus/show.html.erb
	<%# @menu.each do |@menu|%>


		<div class="row">
			<div class="col-md-4">
				<div class="label label-default">名字：</div>
			</div>
			<div class="col-md-8">
				<div><%=@menu.name %></div>
			</div>
		</div>
		<div class="row">
			<div class="col-md-4">
				<div class="label label-default">價錢</div>
			</div>
			<div class="col-md-8">
				<div><%=@menu.price %></div>
			</div>
		</div>
		<div class="row">
			<div class="col-md-4">
				<div class="label label-default">上架時間</div>
			</div>
			<div class="col-md-8">
				<div><%=@menu.ready_time %></div>
			</div>
		</div>
		<div class="row">
			<div class="col-md-4">
				<div class="label label-default">下架時間</div>
			</div>
			<div class="col-md-8">
				<div><%=@menu.remove_time %></div>
			</div>
		</div>
		<div class="row">
			<div class="col-md-4">
				<div class="label label-default">順序</div>
			</div>
			<div class="col-md-8">
				<div><%=@menu.orderby %></div>
			</div>
		</div>
		<div class="row">
			<div class="col-md-4">
				<div class="label label-default">類型</div>
			</div>
			<div class="col-md-8">
				<div><%=@menu.tag %></div>
			</div>
		</div>
		<div class="row">
			<div class="col-md-12">
				<div class="btn btn-default im-centered">
					<%= link_to "index",menus_path %>
				</div>
			</div>
		</div>
	<%# end %>

app/views/restaurants/_form.html.erb
			<%#=params.inspect%>
			<% if @restaurant.errors.any? %>
			      <ul class="row">
			      <% @restaurant.errors.full_messages.each do |msg| %>
			        <li><%= msg %></li>
			      <% end %>
			      </ul>
			<% end %>

			<div class="row">
				<div class="col-md-1">
					<%= f.label :name,"名字" %>
				</div>
				<div class="col-md-3">
					<%= f.text_field :name,:class=>"form-control" %>
				</div>
				<div class="col-md-1">
					<%= f.label :location,"位置" %>
				</div>
				<div class="col-md-7">
					<%= f.text_field :location,:class=>"form-control" %>
				</div>
			</div>
			<div class="row">
				<div class="col-md-2">
					<%= f.label :minmoney,"最低金額" %>
				</div>
				<div class="col-md-2">
					<%= f.number_field :minmoney,:class=>"form-control" %>
				</div>
				<div class="col-md-1">
					<%= f.label :uploadtime,"上傳時間" %>
				</div>
				<div class="col-md-3">
					<%= f.datetime_local_field :uploadtime,:class=>"form-control" %>
				</div>
				<div class="col-md-1">
					<%= f.label :opening,"開幕時間" %>
				</div>
				<div class="col-md-3">
					<%= f.date_field :opening,:class=>"form-control" %>
				</div>
			</div>
			<div class="row">
				<div class="col-md-1">
					<%= f.label :description,"描述" %>
				</div>
				<div class="col-md-11">
					<%= f.text_area :description,:class=>"form-control" %>
				</div>
			</div>
			<div class="row">
				<div class="col-md-12 text-center">

					<%= f.submit("送出") %>
				</div>
			</div>

app/views/restaurants/edit.html.erb
<%=form_for @restaurant ,:url=>restaurant_path(@restaurant),:method=>:patch do |f|%>

<%= render :partial=>'form',:locals=>{ :f=>f} %>

<%= f.submit("送出") %>

<% end %>

app/views/restaurants/index.html.erb
	<div class="well">
		<div class="row">
			this is a test col.
		</div>
	</div>
	<div class="new">
		<div class="row">
		<% if params[:id].nil? %>
		<%=form_for @restaurant ,:url=>restaurants_path do |f|%>
			<%= render :partial=>'form',:locals=>{ :f=>f} %>
		<% end %>
		<% else %>
			<%=form_for @restaurant ,:url=>restaurant_path(@restaurant),:method=>:patch do |f|%>
			<%= render :partial=>'form',:locals=>{ :f=>f} %>
			<% end %>
		<% end %>
		</div>
		<div class="row">

		</div>
	</div>
<div class="row">
	<div class="col-md-12"><%= link_to "new",new_restaurant_path,:class=>"btn btn-default" %>
	</div>
</div>
<table class="table table-striped">
	<thead >
		<tr>
			<th class="col-md-2">名字</th>
			<th class="col-md-6">位置</th>
			<th class="col-md-4"></th>
		</tr>
	</thead><!--thead-->
	<tbody class="tbody">
		<% @restaurants.each do |f| %>
		<tr >
			<td class="col-md-2"><%=f.name %></td>
			<td class="col-md-6"><%=f.location%></td>
			<td class="col-md-4">
				<div class="btn-group">
						<%= link_to "show", restaurant_path(f),:class=>"btn btn-primary" %>
						<%#= link_to "edit", edit_restaurant_path(f),:class=>"btn btn-default" %>
						<%= link_to "edit", edit_restaurant_path(f,:page=>params[:page]),:class=>"btn btn-default" %>
						<%= link_to "delete", restaurant_path(f),:method=>:delete,:class=>"btn btn-danger" %>
				</div><!--btn-group-->
			</td>
		</tr>
	<% end %>
	</tbody><!--tbody-->
</table><!--table-->
<div class="row">
	<div class="col-md-12 text-center"><%= paginate @restaurants %></div>
</div>

app/views/restaurants/new.html.erb
<%=form_for @restaurant ,:url=>restaurants_path do |f|%>
<%= render :partial=>'form',:locals=>{ :f=>f} %>

<%= f.submit("送出") %>
<% end %>

app/views/restaurants/show.html.erb
	<%# @restaurant.each do |@restaurant|%>


		<div class="row">
			<div class="col-md-4">
				<div class="label label-default">名字：</div>
			</div>
			<div class="col-md-8">
				<div><%=@restaurant.name %></div>
			</div>
		</div>
		<div class="row">
			<div class="col-md-4">
				<div class="label label-default">位置：</div>
			</div>
			<div class="col-md-8">
				<div><%=@restaurant.location %></div>
			</div>
		</div>
		<div class="row">
			<div class="col-md-4">
				<div class="label label-default">最低金額：</div>
			</div>
			<div class="col-md-8">
				<div><%=@restaurant.minmoney %></div>
			</div>
		</div>
		<div class="row">
			<div class="col-md-4">
				<div class="label label-default">描述：</div>
			</div>
			<div class="col-md-8">
				<div><%=@restaurant.description %></div>
			</div>
		</div>
		<div class="row">
			<div class="col-md-12">
				<div class="btn btn-default im-centered">
					<%= link_to "index",restaurants_path %>
				</div>
			</div>
		</div>
	<%# end %>